### ISSUE TITLE
Reload Quassel (via SIGHUP) when the SSL certificate changes

### ISSUE THREAD

**Issue by xesxen** [linuxserver/docker-quassel-core#22]
On my system, I use a certificate signed by LetsEncrypt. This is done using a different container that handles certificate generation for NGinx (Web).

As I want a valid certificate on my server, I currently copy over the file (certificate) periodically to /config/quasselCert.pem in the container. Quassel however does not "notice" this and continues to serve connections with the old certificate, which obviously will expire at some point.

Therefore, I would want to have this container do the following:
- Reload Quassel-core via a SIGHUP signal when the cert changes. See [this](https://github.com/quassel/quassel/commit/25a3ae50ac0d9835283e4f5f10fcfcc10ed5575d) commit for proof that Quassel actually supports this feature. Using inotify might be a good way to do this.

**Comment by sparklyballs** [comment]
or restart the container rather than add unnecessary complexity

**Comment by ShaRose** [comment]
Just as a heads up for anyone else who wants to update certificates without having to restart the container and disrupting communication for existing users (or just quassel's connection to any irc servers it's on), you can use docker exec to fire the sighup signal.

docker exec -i -t name-of-your-quassel-container /bin/sh -c 'kill -SIGHUP $(pidof quasselcore)'
