### ISSUE TITLE
The Image tagged latest doesn't use the latest quassel-core version.

### ISSUE THREAD

**Issue by MankoMR** [linuxserver/docker-quassel-core#27]
The Image tagged latest doesn't use the latest quassel-core version.
It runs quassel core v0.12.5 instead of quassel core v0.13.0.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by fakuivan** [comment]
#26 is open for that, help is welcome
