### ISSUE TITLE
Vulnerabilities in Quassel version used

### ISSUE THREAD

**Issue by Toucan-Sam** [linuxserver/docker-quassel-core#35]
The current version of this container is default configured to quassel-core 0.12.4, which has known vulnerabilities.
https://quassel-irc.org/node/130

I may do a pull request later with fixes if someone else hasn't already, but wanted to log issue before I forgot.

Edit: Seems to be fixed already in the repo, but not published to docker hub.
```
FROM lsiobase/alpine:3.6
MAINTAINER sparklyballs

# package versions
ARG QUASSEL_VERSION="0.12.4"
```

**Comment by CHBMB** [comment]
Looks like Dockerhub haven't updated the dockerfile for a long time.  The latest versions are there.

https://hub.docker.com/r/linuxserver/quassel-core/tags

I suspect the Dockerfile on the hub is a remnant from before we switched to a multiarch pipeline
