### ISSUE TITLE
User Initialization: No admin user

### ISSUE THREAD

**Issue by lukas-mika** [linuxserver/docker-quassel-core#36]
Hi there,

just fired up a container of this, but I'm not able to get the admin user registered.
The container comes up just fine, but when I connect the client (as described in the README.md) - both on debian client and android phone, it just asks for user credentials instead of letting me create the first user.
quasselcore does receive the connection attempt, but only fires the error `Invalid login attempt from 12.34.56.78 as "user"`.

The container is run on a debian server using a compose file:

    ---
    version: "2"
    services:
      quassel-core:
        image: linuxserver/quassel-core
        container_name: quassel-core
        environment:
          - PUID=107
          - PGID=999
          - TZ=Europe/Berlin
          - RUN_OPTS=--config-from-environment
          - DB_BACKEND=SQLite
          - AUTH_AUTHENTICATOR=Database
        volumes:
          - /var/docker/quassel-core:/config
        ports:
          - 4242:4242
          - 113:10113
        restart: unless-stopped

Relevant files are written to `/var/docker/quassel-core/`, so that's fine.

Any idea of what might be wrong with this?

Cheers!

**Comment by lukas-mika** [comment]
Alright, found the solution (or at least a work-around):
You need to start the container at least once _without_ the `RUN_OPTS`.
Once you have connected and configured your admin account, you can go back, adjust your compose file and start again with the `RUN_OPTS` configured.

Just in case somebody cares...

**Comment by jtfidje** [comment]
> Alright, found the solution (or at least a work-around):
> You need to start the container at least once _without_ the `RUN_OPTS`.
> Once you have connected and configured your admin account, you can go back, adjust your compose file and start again with the `RUN_OPTS` configured.
> 
> Just in case somebody cares...

I very much cared - thanks alot!

**Comment by MathyV** [comment]
Just chiming in here for people who are experiencing difficulties with creating the initial user (as I also struggled a bit to get going):

My setup is docker-compose based using postgres, here's how I did it:
* just configure the docker-compose.yml as described in the README / on docker hub
* If using postgres make sure your db is started (if you put it in the same file like me) but don't start quassel yet
* run `docker-compose run --rm --entrypoint quasselcore <name-of-service> --config-from-environment -c /config --add-user` (replace `<name-of-service>` with your service)
* enter your username and password of choice
* `docker-compose up -d`

**Comment by darovic** [comment]
For those using this image on Unraid (like I was), you can simply exclude the `--configure-from-environment` flag and run all your configuration in the wizard on first connect.

Perhaps this should be in the docs?

**Comment by i-am-at0m** [comment]
It should also be noted that you can't do that first connection from a web instance that you just setup with the same docker-compose unfortunately.

**Comment by jinmiaoluo** [comment]
If you plan to create containers using docker cli instead of using docker compose, you can refer to the following steps:

Step 1: Launch a temporary container

```bash
# Change "/srv/quassel/config" to the actual volume or path.
docker run --rm -ti \
  --name=quassel-core \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Asia/Shanghai \
  -e RUN_OPTS="--config-from-environment --ident-daemon --ident-port 10113 --ident-listen 0.0.0.0" \
  -e DB_BACKEND=SQLite \
  -e AUTH_AUTHENTICATOR=Database \
  -p 4242:4242 \
  -p 10113:10113 \
  -v /srv/quassel/config:/config \
  --entrypoint ash \
  linuxserver/quassel-core:latest
```

Step 2: Create a user in the interactive interface of the container.

```bash
quasselcore --configdir=/config --add-user
```

Step 3: After exiting with ctrl+d, create the formal container.

```bash
docker run -d \
  --name=quassel-core \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Asia/Shanghai \
  -e RUN_OPTS="--config-from-environment --ident-daemon --ident-port 10113 --ident-listen 0.0.0.0" \
  -e DB_BACKEND=SQLite \
  -e AUTH_AUTHENTICATOR=Database \
  -p 4242:4242 \
  -p 10113:10113 \
  -v /srv/quassel/config:/config \
  --restart unless-stopped \
  linuxserver/quassel-core:latest
```
