### ISSUE TITLE
Blowfish encryption no longer works

### ISSUE THREAD

**Issue by galfwender** [linuxserver/docker-quassel-core#38]
I just upgraded from 0.12 to 0.13 and blowfish encryption no longer works.  When trying to set or view a key the following message is displayed:

Error: Setting an encryption key requires Quassel to have been built with support for the Qt Cryptographic Architecture (QCA) library. Contact your distributor about a Quassel package with QCA support, or rebuild Quassel with QCA present.

**Comment by CHBMB** [comment]
> Quassel supports ECB and CBC modes (default is ECB in versions <0.13 and CBC in versions >=0.13).

From the Quassel website: https://bugs.quassel-irc.org/projects/quassel-irc/wiki/Blowfish_Encryption_Manual

**Comment by galfwender** [comment]
I am not sure how that is relevant.  Quassel 0.13 supports both ECB and CBC but must be built specifically to enable this.  /setkey returns the above error message with the latest version of this docker container, regardless of which mode is default, but did not when it contained 0.12.  The error message clearly states that it was not built with support for blowfish.

**Comment by CHBMB** [comment]
Yeah, we're looking at it.  How old was the container you were using before?  We updated a long time ago.

**Comment by galfwender** [comment]
I believe I started using it prior to the launch of 0.13, so around November 2018

**Comment by CHBMB** [comment]
Oh wow, that was a long time ago.

**Comment by STX2k** [comment]
+1 for Blowfish fix :)

**Comment by STX2k** [comment]
Any Update on this ?

**Comment by Motophan** [comment]
[redacted]

**Comment by Motophan** [comment]
.

**Comment by Motophan** [comment]
.
