### ISSUE TITLE
DB_PGSQL_PASSWORD environment variable is ignored (fe_sendauth: no password supplied)

### ISSUE THREAD

**Issue by mrzapp** [linuxserver/docker-quassel-core#40]
## Expected Behavior
The image starts and connects to PostgreSQL server

## Current Behavior
The image fails with an error: `fe_sendauth: no password supplied`

## Steps to Reproduce
Follow the instructions provided in this project for setting up PostgreSQL with environment variables

## Problem
The issue seems to be [here](https://github.com/linuxserver/docker-quassel-core/blob/master/root/etc/cont-init.d/40-config#L15), the password variable is overridden as an empty string

**Comment by homerr** [comment]
Sorted in #47
