### ISSUE TITLE
suggesting documentation causes permanent ban from discord

### ISSUE THREAD

**Issue by Motophan** [linuxserver/docker-quassel-core#45]
suggested that the docs reflect that you need a db for this app or it will stop working in about 6 months. 

https://github.com/linuxserver/docker-nextcloud/issues/200

along w/ this container I had two separate I was trying to explain. I was told something to the effect of "that's not an issue with our container" and I said something to the effect of "that's correct, but no matter what you say it won't change the fact that the container will stop responding in about 6 months and have to be redone w/ a fresh sqlite db"

at that time I was permanently banned 

now I totally understand that sometimes people make decisions to go in One direction and not the other direction. if Linux server had no intention of adding this to the documentation that's fine, but that doesn't really warrant a permanent ban. I mean I'm not a moderator but that seems a little severe for making a genuine suggestion. 

can I be unbanned?

**Comment by homerr** [comment]
No idea what you are on about here, and @aptalca answered your ban question elsewhere. If you wish to re-open an issue as per the template with the required information and what it is that needs changing, we'll be happy to review.
