### ISSUE TITLE
Build 0.14-rc1 in a tag

### ISSUE THREAD

**Issue by kaechele** [linuxserver/docker-quassel-core#46]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
An image with the [0.14-rc1 codebase](https://github.com/quassel/quassel/releases/tag/0.14-rc1) is built and tagged `0.14`.
Some changes to the Dockerfile are required for this: https://github.com/kaechele/docker-quassel-core/commit/1e83ce85f1c09f21f7e40a04105f5073b7abacdc

## Current Behavior
Currently, only stable releases (0.13) are built. Quassel's release cycle moves extremely slowly but 0.14 does contain some features (such as IRCv3 enhancements), Prometheus metrics or HAProxy support that I assume some people would enjoy using.

## Alternatives Considered
I have cloned the repository and built my own version locally using the 0.14-rc1 code. It works well for me.

**Comment by optiz0r** [comment]
https://github.com/optiz0r/docker-quassel-core/tree/feature_0.14-rc2 builds 0.14-rc2. I had to update the dependencies, and copy some additional libraries from the build-stage image to the final image. This appears to be working fine for me so far, but the core has only been up and running for 5mins.

**Comment by kaechele** [comment]
Should work fine. I've been using this for a few months now without issues: https://github.com/kaechele/docker-quassel-core/commits/0.14-rc1
